services:
  item-manager:
    container_name: item-manager
    build: .
    volumes:
      - ./src:/var/www/html
      - ./apache/main.conf:/etc/apache2/sites-available/main.conf
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 81:80
    depends_on:
      - test-db
  test-db:
    container_name: test-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: item-manager-local